spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    from: no-reply@mHide.ru
    host: localhost
    port: 3025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true

security:
  jwt:
    secret: Y3VwZXItc2VjcmV0LXByaXphZnplZHItdmVyeS1sb25nLXNlY3JldA==
    expirationMs: 3600000000
    refreshExpirationMs: 86400000

logging:
  level:
    root: info
    org.springframework.web: info
    com.mHide: debug
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

otp:
  check-expired-delay-ms: 100000
  file:
    storage-path: ./otp-storage
    filename: otp_codes.log
    max-file-size: 10MB
    max-backup-files: 5
  code:
    length: 6
    ttl-seconds: 300

telegram:
  bot:
    token: 7765985917:AAHjOGosDKl4z98mrNrkljGXfr3pATaSExY
    enable: true

smpp:
  host: localhost
  port: 2775
  system_id: smppclient1
  password: password
  system_type: OTP
  source_addr: OTPService
  max-retries: 3
  timeout-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true